name: Distributed File Executor
server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 8091
  adminConnectors:
    - type: http
      port: 8092
client:
  port: 5001
  host: 127.0.0.1
  username: 1234abcd
bootstrapServer:
  port: 55555
  host: 127.0.0.1
udpServer:
  port: 9000
  host: 127.0.0.1