name: Distributed File Executor

# === DropWizard Configs ===
server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091

# === Client Configs ===
client:
  port: 5001
  host: 127.0.0.1
  username: 1234abcd

# === BootstrapServer Configs ===
bootstrapServer:
  port: 55555
  host: 127.0.0.1

# === Network Configs
hops: 4