name: Distributed File Executor

# === DropWizard Configs ===
server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091

# Stream logs to a backend node.js server
logging:
  level: INFO
  appenders:
    - type: tcp
      host: localhost
      port: 3000
      connectionTimeout: 500ms
      immediateFlush: true
      sendBufferSize: 8KiB
    - type: console
      threshold: ALL
      queueSize: 512
      discardingThreshold: 0
      timeZone: UTC
      target: stdout
      logFormat: "%-5p [%d{ISO8601,UTC}] %c: %m%n%rEx"

# === Client Configs ===
client:
  port: 5001
  host: 127.0.0.1
  username: 1234abcd
  files:
    - Shadows
    - Sapiens
    - Deus
    - Tamed
    - Cosmos
    - OutgrowingGod
    - Habit
    - CosmicConnection
    - ThinkingFastAndSlow
    - MansSearchForMeaning
    - DragonsOfEden
    - SurelyYoureJoking
    - RedLimit
    - FutureOfHumanity
    - EinstinesCosmos
    - ThirdWave
    - SpinningMagnet
    - BookOfUniverses
    - 12RulesForLife
    - ConstantsOfNature
    - PhysicsOfFuture
    - TwoSidesOfTheMoon
    - Money
    - OutgrowingGod
    - OnGovernment
    - OnOriginsOfSpecies

      # === BootstrapServer Configs ===
bootstrapServer:
  port: 55555
  host: 127.0.0.1

# === Network Configs
hops: 4