name: Distributed File Executor

# === DropWizard Configs ===
server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 8094
  adminConnectors:
    - type: http
      port: 8095

# === Client Configs ===
client:
  port: 5003
  host: 127.0.0.1
  username: 1234abcd
  files:
    - Shadows
    - Sapiens
    - Deus
    - Tamed
    - Cosmos
    - OutgrowingGod
    - Habit
    - CosmicConnection
    - ThinkingFastAndSlow
    - MansSearchForMeaning
    - DragonsOfEden
    - SurelyYoureJoking
    - RedLimit
    - FutureOfHumanity
    - EinstinesCosmos
    - ThirdWave
    - SpinningMagnet
    - BookOfUniverses
    - 12RulesForLife
    - ConstantsOfNature
    - PhysicsOfFuture
    - TwoSidesOfTheMoon
    - Money
    - OutgrowingGod
    - OnGovernment
    - OnOriginsOfSpecies

      # === BootstrapServer Configs ===
bootstrapServer:
  port: 55555
  host: 127.0.0.1

# === Network Configs
hops: 4