name: Distributed File Executor
server:
  applicationConnectors:
    - type: http
      port: 8091
  adminConnectors:
    - type: http
      port: 8092
ports:
  port: 5001
  host: 127.0.0.1
  username: 1234abcd
bootstrapServer:
  port: 55555
  host: 127.0.0.1
