name: Distributed File Executor
server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 8093
  adminConnectors:
    - type: http
      port: 8094
ports:
  port: 5002
  host: 127.0.0.1
  username: 1234abcd
bootstrapServer:
  port: 55555
  host: 127.0.0.1
udpServer:
  port: 9001
  host: 127.0.0.1
