name: Distributed File Executor
server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091
client:
  port: 5001
  host: 127.0.0.1
  username: 1234abcd
bootstrapServer:
  port: 55555
  host: 127.0.0.1
hops: 4
#webPort: 0000