name: Distributed File Executor
server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 8095
  adminConnectors:
    - type: http
      port: 8096
client:
  port: 5003
  host: 127.0.0.1
  username: 1234abcd
bootstrapServer:
  port: 55555
  host: 127.0.0.1
hops: 4
webPort: 8095